### ISSUE TITLE
공통 타이틀 컴포넌트를 구현한다.

### ISSUE THREAD

**Issue by kyungmim** [KDT-hahahoho/kdt_frontend#156]
### ✅ Tasks

- [x]  타이틀 컴포넌트 생성
- [x] 타이틀 컴포넌트 UI 작업
- [x] 타이틀 프롭 타입 설정
### 🙋🏻 More
*No response*
