### ISSUE TITLE
공통 타이틀 컴포넌트를 적용한다.

### ISSUE THREAD

**Issue by kyungmim** [KDT-hahahoho/kdt_frontend#167]
### ✅ Tasks

공통 타이틀 적용
- [x] 메인 화면
- [x] 심리상담
- [x] 심리 상담 목록
- [x] 스트레스 척도 검사 결과 리스트
- [x] 스트레스 척도 검사 결과 화면

### 🙋🏻 More
*No response*
