### ISSUE TITLE
회원가입 중 약관동의 컴포넌트를 만들고 최적화를 진행한다.

### ISSUE THREAD

**Issue by woojoung1217** [KDT-hahahoho/kdt_frontend#23]
### ✅ Tasks

- [x]  회원가입 로직 수정 및 최적화
- [x]  약관동의 컴포넌트 구현
- [x] 공통 컴포넌트 설명 

### 🙋🏻 More
*No response*
