### ISSUE TITLE
난임 스트레스 척도 컴포넌트를 생성하고 기능을 구현한다.

### ISSUE THREAD

**Issue by s0zzang** [KDT-hahahoho/kdt_frontend#24]
### 📄 Describe

난임 스트레스 척도 기능을 구현한다.

### ✅ Tasks

- [x] 난임 스트레스 척도 컴포넌트 생성
- [x] 난임 스트레스 척도 라우트 생성
- [x] 검사 진행 정도 구현
- [x] 검사지 구현
- [x] 점수 산출
- [x] 산출된 점수 POST
- [ ] 진행도 노출 (2순위로 추후 진행)
- [x] GPT를 통해 난임 척도 결과에서 핵심신념 추출
- [x] 핵심신념 POST

### 🙋🏻 More
*No response*
