### ISSUE TITLE
감정기록 기능을 구현한다.

### ISSUE THREAD

**Issue by JWJung-99** [KDT-hahahoho/kdt_frontend#27]
### 📄 Describe
감정기록 기능을 구현한다.

### ✅ Tasks

- [ ] 감정입력 프로그레스바 구현 (중요도 **중**)
- [ ] 채팅창 새로운 대화가 올라오면 스크롤바 맨 밑으로 (중요도 **하**)
- [ ] 입력창 입력 길이가 늘어나면 입력창 크게 (중요도 **하**)
- [x] 감정입력 채팅창 구현
- [x] 입력 메시지 상태 관리

### 🙋🏻 More
*No response*
