### ISSUE TITLE
상대에게 한 마디 작성 페이지를 구현한다.

### ISSUE THREAD

**Issue by JWJung-99** [KDT-hahahoho/kdt_frontend#35]
### 📄 Describe
- 상대에게 한 마디 구현

### ✅ Tasks
- [x] 감정기록 레이아웃 수정
- [x] 감정기록 시 작성하지 않으면 다음 페이지로 이동할 수 없도록 수정
- [x] 감정기록 전역 상태 등록
- [x] 상대에게 한 마디 페이지 구현

### 🙋🏻 More
*No response*
