### ISSUE TITLE
난임 스트레스 척도 목록을 구현한다.

### ISSUE THREAD

**Issue by s0zzang** [KDT-hahahoho/kdt_frontend#48]
### 📄 Describe

난임 스트레스 척도 목록을 구현한다.

### ✅ Tasks

- [x] 실제 데이터 GET
- [x] 목록 노출
- [x] 통계 차트 구현
- [x] 모달(한달에 한번 검사 권장) 노출

### 🙋🏻 More
*No response*
