### ISSUE TITLE
난임 스트레스 척도 검사 결과 화면 컴포넌트 생성 및 기능을 구현한다.

### ISSUE THREAD

**Issue by kyungmim** [KDT-hahahoho/kdt_frontend#49]
### 📄 Describe

난임 스트레스 척도 검사 결과 화면 구현

### ✅ Tasks

- [x] 스트레스 척도 검사 결과 컴포넌트 생성
- [x] 스트레스 결과 화면 라우트 생성
- [x] 스트레스 척도 검사 결과 UI 작업 
- [x] 스트레스 척도 이전 검사와 현재 검사 비교 
- [x]  스트레스 척도 결과 시각화 적용

### 🙋🏻 More
*No response*
