### ISSUE TITLE
감정분석 전역 상태 전달을 테스트한다.

### ISSUE THREAD

**Issue by JWJung-99** [KDT-hahahoho/kdt_frontend#62]
### 📄 Describe
감정분석 전역 상태 전달 테스트

### ✅ Tasks
- [x] 감정분석 전역 상태 테스트
- [x] 감정분석 -> 미션 선택 페이지로 이동
- [x] 감정분석 요청 후 임시 로딩 컴포넌트 추가

### 🙋🏻 More
*No response*
