### ISSUE TITLE
감정 분석 결과 페이지를 구현한다

### ISSUE THREAD

**Issue by HuiseonDev** [KDT-hahahoho/kdt_frontend#65]
### 📄 Describe
감정 분석 결과 페이지를 구현한다

### ✅ Tasks

- [ ]  감정 분석 결과 페이지 UI 구현
- [ ]  감정 분석 결과 페이지 
- [x]  라우트 생성
- [ ] GET 데이터 통신
- [ ] 데이터 시각화

### 🙋🏻 More
*No response*
