### ISSUE TITLE
AI 심리상담 프롬프팅을 고도화한다.

### ISSUE THREAD

**Issue by s0zzang** [KDT-hahahoho/kdt_frontend#78]
### ✅ Tasks

- [x] 주고 받은 메시지를 전달하여 맥락 유지
- [x] 전체 맥락 요약시 사례개념화 포맷 적용
- [x] 채팅 전송 시 스크롤 위치 조정
- [x] 이전 상담 내역이 있는 경우, gpt에게 전달
- [x] 이전 상담 내역이 있는 경우, UI 표시

### 🙋🏻 More
*No response*
